### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rpasek** [NeatMonster/slabdbg#2]
Hi!
I'm interested in using slabdbg to debug a memory issue that I am having but I'm unable to do so because there is no license included in this repo. Could you add a license to this project?

Thanks!
Richard

**Comment by clark-ja** [comment]
@NeatMonster same question here. Would it be possible for you to add a license, even if you choose a restrictive one, so we can know whether or not it is ok to reuse and modify your code?

**Comment by NeatMonster** [comment]
@rpasek @theguy147 Sorry for the late reply. I've just added a license file (MIT) to the repository.
