### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by Knaithe** [NeatMonster/slabdbg#4]
gdb version：GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
OS version：ubuntu 18.04
![image](https://user-images.githubusercontent.com/22469662/177449014-43c0df39-cba0-43c7-b8b3-539f1e870394.png)

**Comment by Pricx** [comment]
Hi, I've met the same question as you. GDB says ` No symbol "memstart_addr" in current context.` in 
```
line 98, in __init__
    self.memstart_addr = gdb.lookup_global_symbol("memstart_addr").value()
AttributeError: 'NoneType' object has no attribute 'value'
```
